version: '3'
services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1884:1884"
    networks:
      - my_network

  mqtt_publisher:
    build:
      context: ./mqtt_publisher
    depends_on:
      - mqtt-broker
    networks:
      - my_network

  mqtt_subscriber:
    build:
      context: ./mqtt_subscriber  # Replace with the path to your MQTT Subscriber code
    depends_on:
      - mqtt-broker
    networks:
      - my_network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my_network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my_network

  fastapi:
    build:
      context: ./fastapi-app  # Replace with the path to your FastAPI app code
    ports:
      - "8000:8000"
    depends_on:
      - mqtt-broker
      - mqtt_subscriber
      - mongo
      - redis
    networks:
      - my_network

networks:
  my_network:
